### ISSUE TITLE
Adding gw shows "not found"

### ISSUE THREAD

**Issue by twister5800** [rogierhofboer/com.ikea.tradfri.gateway#14]
When installed app in Homey, adding hostname and sec key, when I press authenticate I get "not found" immidiately.

**Comment by rogierhofboer** [comment]
Do you use the desktop app?
It is the only one that really works well for this.

**Comment by twister5800** [comment]
Yes, the newest 1.0.4, I get this:

![image](https://user-images.githubusercontent.com/13104344/49357317-24270400-f6cf-11e8-9d64-403c43f94f82.png)


Tried on two computers.

**Comment by rogierhofboer** [comment]
Do you still have this problem? Please try 0.0.10 beta (or wait a bit for 0.0.11 beta).
The procedure is press 'Discover' the the IP of the gateway is shown at the Hostname.
If this doesn't work (on some networks the gateway discovery does not work, probably due to strict firewall setings) try to find out the IP address of your gateway (look at the DHCP leases in your router.
and put the IP address in the hostname field. 
Put the Security code on the back of the gateway  in the security code field and press authenticate.
Identity and PSK should be filled now.
Press Save

**Comment by rogierhofboer** [comment]
Do you still have this problem? Please close this issue if your problem is resolved. Or contact me on the athomcommunity slack so we can have a look together.

**Comment by rogierhofboer** [comment]
Closing due to no response and no other reports of this issue.
